#! /bin/sh

#*******************************************************************************#
#                                                                               #
#                                                          :::      ::::::::    #
#     rubynette                                          :+:      :+:    :+:    #
#                                                      +:+ +:+         +:+      #
#     By: evilsbol <evilsbol@student.42.fr>          +#+  +:+       +#+         #
#                                                  +#+#+#+#+#+   +#+            #
#     Created: 2013/12/16 20:20:35 by evilsbol          #+#    #+#              #
#     Updated: 2013/12/16 20:20:40 by evilsbol         ###   ########.fr        #
#                                                                               #
#*******************************************************************************#

#bin executable inspired by 'check' by stherman of https://github.com/42School

rubynette.rb $@
